cache:
  event: ["~/.m2"]

shared:
  annotations:
    screwdriver.cd/cpu: TURBO
    screwdriver.cd/ram: TURBO
  image: maven:3.6.3-adoptopenjdk-8

jobs:
  pull-commit:
    requires: [~pr]
    steps:
      - header: echo "Starting the pipeline"
      - lua-install: apt-get update -qy && apt-get install -y lua5.2
      - build: ./screwdriver/mvn-build.bash
    environment:
      GIT_SHALLOW_CLONE: false

  master-commit:
    requires: [~commit]
    steps:
      - header: echo "Starting the commit pipeline"
      - debug: |
          echo "Master Commit : ${SD_EVENT_ID} ${SD_JOB_NAME} ${SD_PARENT_BUILD_ID}"
      - lua-install: apt-get update -qy && apt-get install -y lua5.2
      - build: ./screwdriver/mvn-build.bash
      - prep-release: apt-get update -y && apt-get install -y python
      - release: ./screwdriver/is_whitelisted.bash && ./screwdriver/tag-for-release.bash
    environment:
      GIT_SHALLOW_CLONE: false

  tag-release:
    secrets:
      - GPG_KEYNAME
      - GPG_PASSPHRASE
      - GPG_ENCPHRASE
      - OSSRH_USER
      - OSSRH_TOKEN
    requires: [~tag:/\d+\.\d+\.\d+/]
    steps:
      - header: echo "Starting the release pipeline"
      - debug: |
         echo "Releasing : ${SD_EVENT_ID} ${SD_JOB_NAME} ${SD_PARENT_BUILD_ID}"
      - lua-install: apt-get update -qy && apt-get install -y lua5.2
      - gpg-install: apt-get update -qy && apt-get install -y gnupg
      - release: ./screwdriver/is_whitelisted.bash
      - build: "screwdriver/scripts/build.sh"
      - publish: "screwdriver/scripts/publish.sh"
