cache:
  event: ["~/.m2"]

shared:
  annotations:
    screwdriver.cd/cpu: TURBO
    screwdriver.cd/ram: TURBO
  image: maven:3.6.3-jdk-8

jobs:
  pull-commit:
    requires: [~pr]
    steps:
      - header: echo "Starting the pipeline"
      - lua-install: apt-get update -qy && apt-get install -y lua5.2
      - build: ./screwdriver/mvn-build.bash

  master-commit:
    requires: [~commit:sd-master, ~tag]
    steps:
      - header: echo "Starting the pipeline"
      - lua-install: apt-get update -qy && apt-get install -y lua5.2
      - build: ./screwdriver/mvn-build.bash
#      - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git /tmp/ci
      - release: ./screwdriver/ci-tag.bash

  release:
    secrets:
      - BINTRAY_USER
      - BINTRAY_API_KEY
    requires: [master-commit]
    steps:
      - header: echo "Starting the pipeline"
      - lua-install: apt-get update -qy && apt-get install -y lua5.2 idea
      - release: ./screwdriver/mvn_deploy.bash
